
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { RiskAnalysisResult } from '@/prompts/risk-analysis';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        paddingBottom: 20,
        textAlign: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 12,
        color: '#64748B',
        marginBottom: 15,
    },
    scoreBadge: {
        alignSelf: 'center',
        padding: '8 20',
        borderRadius: 20,
        backgroundColor: '#F1F5F9',
        marginTop: 10,
    },
    scoreText: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    section: {
        marginTop: 20,
        marginBottom: 10,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#0F172A',
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
        paddingBottom: 5,
    },
    text: {
        fontSize: 10,
        color: '#334155',
        lineHeight: 1.5,
        marginBottom: 5,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 10,
    },
    column: {
        flexDirection: 'column',
        flex: 1,
        paddingRight: 10,
    },
    bulletPoint: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    bullet: {
        width: 3,
        height: 3,
        backgroundColor: '#64748B',
        borderRadius: 50,
        marginTop: 5,
        marginRight: 8,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 8,
        color: '#94A3B8',
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
        paddingTop: 10,
    }
});

interface RiskReportPDFProps {
    result: RiskAnalysisResult;
    projectTitle?: string;
}

export const RiskReportPDF = ({ result, projectTitle }: RiskReportPDFProps) => {
    const riskColor =
        result.riskLevel === 'High' ? '#EF4444' :
            result.riskLevel === 'Medium' ? '#F97316' :
                '#22C55E';

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>{projectTitle || "Project Risk Analysis"}</Text>
                    <Text style={styles.subtitle}>Generated by RiskLens AI</Text>

                    <View style={[styles.scoreBadge, { backgroundColor: result.riskLevel === 'High' ? '#FEF2F2' : result.riskLevel === 'Medium' ? '#FFF7ED' : '#F0FDF4' }]}>
                        <Text style={[styles.scoreText, { color: riskColor }]}>
                            {result.riskScore}/100 • {result.riskLevel} Risk
                        </Text>
                    </View>
                </View>

                {/* Executive Summary */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Executive Summary</Text>
                    <Text style={styles.text}>{result.summary}</Text>
                </View>

                {/* Red Flags */}
                <View style={styles.section}>
                    <Text style={[styles.sectionTitle, { color: '#EF4444' }]}>Critical Red Flags</Text>
                    {result.redFlags.map((flag, i) => (
                        <View key={i} style={styles.bulletPoint}>
                            <Text style={{ color: '#EF4444', marginRight: 8, fontSize: 10 }}>•</Text>
                            <Text style={styles.text}>{flag}</Text>
                        </View>
                    ))}
                </View>

                {/* Detailed Analysis */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Detailed Assessment</Text>

                    <View style={{ marginBottom: 10 }}>
                        <Text style={[styles.text, { fontWeight: 'bold' }]}>Scope & Technical</Text>
                        <Text style={styles.text}>{result.technicalAnalysis}</Text>
                    </View>

                    <View style={{ marginBottom: 10 }}>
                        <Text style={[styles.text, { fontWeight: 'bold' }]}>Budget & Timeline</Text>
                        <Text style={styles.text}>{result.budgetAnalysis}</Text>
                    </View>

                    <View style={{ marginBottom: 10 }}>
                        <Text style={[styles.text, { fontWeight: 'bold' }]}>Client Signals</Text>
                        <Text style={styles.text}>{result.clientAnalysis}</Text>
                    </View>
                </View>

                {/* Action Plan */}
                <View style={styles.row}>
                    <View style={styles.column}>
                        <Text style={[styles.sectionTitle, { fontSize: 12 }]}>Negotiation Strategy</Text>
                        {result.negotiationPoints.map((point, i) => (
                            <View key={i} style={styles.bulletPoint}>
                                <Text style={{ marginRight: 5, fontSize: 10 }}>→</Text>
                                <Text style={styles.text}>{point}</Text>
                            </View>
                        ))}
                    </View>
                    <View style={styles.column}>
                        <Text style={[styles.sectionTitle, { fontSize: 12 }]}>Questions to Ask</Text>
                        {result.questionsToAsk.map((q, i) => (
                            <View key={i} style={styles.bulletPoint}>
                                <Text style={{ marginRight: 5, fontSize: 10 }}>?</Text>
                                <Text style={styles.text}>{q}</Text>
                            </View>
                        ))}
                    </View>
                </View>

                {/* Footer */}
                <Text style={styles.footer}>
                    This report represents an AI-based assessment and should not be considered legal or financial advice.
                    © {new Date().getFullYear()} RiskLens
                </Text>
            </Page>
        </Document>
    );
};
