
import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { RiskAnalysisResult } from '@/prompts/risk-analysis';

// Register fonts if needed
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf' });

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#ffffff',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#cccccc',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#111827',
    },
    subtitle: {
        fontSize: 12,
        color: '#6b7280',
    },
    section: {
        marginVertical: 10,
        padding: 5,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#374151',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingBottom: 5,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        fontSize: 10,
        color: '#6b7280',
        width: 100,
    },
    value: {
        fontSize: 10,
        color: '#111827',
        flex: 1,
    },
    riskScoreContainer: {
        marginVertical: 15,
        padding: 15,
        backgroundColor: '#f3f4f6',
        borderRadius: 5,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    riskScoreLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#374151',
    },
    riskScoreValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#000000',
    },
    text: {
        fontSize: 10,
        lineHeight: 1.5,
        marginBottom: 8,
        color: '#374151',
    },
    clauseContainer: {
        marginBottom: 10,
        padding: 8,
        backgroundColor: '#f9fafb',
        borderLeftWidth: 3,
        borderLeftColor: '#3b82f6',
    },
    clauseTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    clauseText: {
        fontSize: 10,
        fontStyle: 'italic',
        marginBottom: 4,
        color: '#4b5563',
    },
    clauseExplanation: {
        fontSize: 9,
        color: '#6b7280',
    },
    list: {
        marginLeft: 15,
    },
    listItem: {
        fontSize: 10,
        marginBottom: 4,
        color: '#374151',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 8,
        color: '#9ca3af',
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        paddingTop: 10,
    }
});

interface RiskReportPDFProps {
    result: RiskAnalysisResult;
    projectTitle: string;
    clientName?: string;
}

export const RiskReportPDF = ({ result, projectTitle, clientName }: RiskReportPDFProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Risk Analysis Report</Text>
                <Text style={styles.subtitle}>Generated by RiskLens AI</Text>
                <Text style={{ fontSize: 10, marginTop: 5, color: '#9ca3af' }}>
                    {new Date().toLocaleDateString()}
                </Text>
            </View>

            {/* Project Details */}
            <View style={styles.section}>
                <View style={styles.row}>
                    <Text style={styles.label}>Project Title:</Text>
                    <Text style={styles.value}>{projectTitle}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Client:</Text>
                    <Text style={styles.value}>{clientName || 'N/A'}</Text>
                </View>
            </View>

            {/* Risk Score */}
            <View style={styles.riskScoreContainer}>
                <Text style={styles.riskScoreLabel}>
                    Risk Level: <Text style={{ color: result.riskLevel === 'High' ? '#ef4444' : result.riskLevel === 'Medium' ? '#f59e0b' : '#10b981' }}>{result.riskLevel}</Text>
                </Text>
                <Text style={styles.riskScoreValue}>{result.riskScore}/100</Text>
            </View>

            {/* Executive Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Executive Summary</Text>
                <Text style={styles.text}>{result.summary}</Text>

                <Text style={{ fontSize: 12, fontWeight: 'bold', marginTop: 10, marginBottom: 5 }}>Recommendation: {result.recommendation}</Text>
            </View>

            {/* Red Flags */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Critical Red Flags</Text>
                {result.redFlags.map((flag, index) => (
                    <Text key={index} style={styles.listItem}>• {flag}</Text>
                ))}
            </View>

            {/* Analysis Details */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Detailed Analysis</Text>

                <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Technical Feasibility</Text>
                <Text style={styles.text}>{result.technicalAnalysis}</Text>

                <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Budget & Scope</Text>
                <Text style={styles.text}>{result.budgetAnalysis}</Text>

                <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Client Signals</Text>
                <Text style={styles.text}>{result.clientAnalysis}</Text>
            </View>

            <Text style={styles.footer}>
                RiskLens - Freelance Identification & Protection System
            </Text>

            <Text render={({ pageNumber, totalPages }) => (
                `${pageNumber} / ${totalPages}`
            )} fixed style={{ position: 'absolute', bottom: 30, right: 30, fontSize: 10, color: 'grey' }} />
        </Page>

        {/* Page 2: Clauses & Strategy */}
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Protective Measures</Text>
            </View>

            {/* Contract Clauses */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Suggested Contract Clauses</Text>
                {result.contractClauses.map((item, index) => (
                    <View key={index} style={styles.clauseContainer}>
                        <Text style={styles.clauseTitle}>{item.title}</Text>
                        <Text style={styles.clauseText}>"{item.clause}"</Text>
                        <Text style={styles.clauseExplanation}>Why: {item.explanation}</Text>
                    </View>
                ))}
            </View>

            {/* Negotiation Strategy */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Negotiation Strategy</Text>
                {result.negotiationPoints.map((point, index) => (
                    <Text key={index} style={styles.listItem}>• {point}</Text>
                ))}
            </View>

            {/* Clarification Questions */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Questions to Ask Client</Text>
                {result.questionsToAsk.map((q, index) => (
                    <Text key={index} style={styles.listItem}>? {q}</Text>
                ))}
            </View>

            <Text style={styles.footer}>
                RiskLens - Freelance Identification & Protection System
            </Text>

            <Text render={({ pageNumber, totalPages }) => (
                `${pageNumber} / ${totalPages}`
            )} fixed style={{ position: 'absolute', bottom: 30, right: 30, fontSize: 10, color: 'grey' }} />
        </Page>
    </Document>
);
